<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NurMarketKassa.Assets</RootNamespace>
    <AssemblyName>NurMarketKassa.Assets</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.*" Condition="Exists('Assets')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

</Project>
