<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>1.2.9</Version>
		<OutputType>WinExe</OutputType>
		<ApplicationIcon>Assets\app-logo.ico</ApplicationIcon>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
		<AssemblyName>NurMarketKassa</AssemblyName>
		<RootNamespace>NurMarketKassa</RootNamespace>
		<Title>Nur Market — Касса</Title>
		<Product>NurMarketKassa</Product>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>None</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishReadyToRun>false</PublishReadyToRun>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\Elkart-logo.png" />
	  <None Remove="Assets\Finca-logo.png" />
	  <None Remove="Assets\Login1.png" />
	  <None Remove="Assets\Mbank-logo.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="10.0.8" />
		<PackageReference Include="System.IO.Ports" Version="10.0.8" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.8" />
		<PackageReference Include="Velopack" Version="1.0.1" />
		<PackageReference Include="MySqlConnector" Version="2.4.0" />
		<PackageReference Include="VirtualizingWrapPanel" Version="2.5.1" />
		<PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\app-logo.png" />
		<Resource Include="Assets\Elkart-logo.png" />
		<Resource Include="Assets\Finca-logo.png" />
		<Resource Include="Assets\Login1.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Assets\Mbank-logo.png" />
	</ItemGroup>

</Project>
